# Copyright (c) 2016 Axel Voitier
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

all: my-zmq-dealer my-zmq-pub my-zmq-sub

APPDIRS += ../../apps
APPS += zmtp

CONTIKI=../../contiki
CONTIKI_WITH_IPV6 = 1
include $(CONTIKI)/Makefile.include
