all: my-zmq-dealer my-zmq-pub my-zmq-sub my-zmq-push my-zmq-pull my-zmq-push-pull my-zmq-pull-connect

APPDIRS += ../../apps
APPS += zmtp

CONTIKI=../../contiki
CONTIKI_WITH_IPV6 = 1
include $(CONTIKI)/Makefile.include
